name: sam-pygame
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - numpy
  - pillow
  - pygame
  - pytorch
  - torchvision
  - pip
  - scipy
  - pip:
      - git+https://github.com/facebookresearch/segment-anything.git
      - opencv-python


# mamba env create -f environment.yml